/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChronischeKrankheitenTS } from './chronische-krankheiten';
import { AuslandArtTS } from './ausland-art';
import { AdresseJaxTS } from './adresse-jax';
import { GeschlechtTS } from './geschlecht';
import { LebensumstaendeTS } from './lebensumstaende';
import { BeruflicheTaetigkeitTS } from './berufliche-taetigkeit';
import { AmpelColorTS } from './ampel-color';
import { KrankenkasseTS } from './krankenkasse';


export interface CreateRegistrierungJaxTS { 
    language?: string;
    geschlecht?: GeschlechtTS;
    name?: string;
    vorname?: string;
    geburtsdatum?: Date;
    adresse?: AdresseJaxTS;
    mail?: string;
    telefon?: string;
    bemerkung?: string;
    krankenkasse?: KrankenkasseTS;
    krankenkasseKartenNr?: string;
    auslandArt?: AuslandArtTS;
    abgleichElektronischerImpfausweis?: boolean;
    contactTracing?: boolean;
    immobil?: boolean;
    chronischeKrankheiten?: ChronischeKrankheitenTS;
    beruflicheTaetigkeit?: BeruflicheTaetigkeitTS;
    lebensumstaende?: LebensumstaendeTS;
    ampelColor?: AmpelColorTS;
    schutzstatus?: boolean;
}

