/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentQueueTypeTS } from './document-queue-type';
import { DocumentQueueStatusTS } from './document-queue-status';


export interface DocumentQueueJaxTS { 
    typ: DocumentQueueTypeTS;
    errorCount: number;
    status: DocumentQueueStatusTS;
    timestampErstellt: Date;
    resultTimestamp?: Date;
    lastError?: string;
    docQueueResultId?: string;
    docQueueResultFilename?: string;
}

