/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfstoffJaxTS } from './impfstoff-jax';
import { MissingForGrundimmunisiertTS } from './missing-for-grundimmunisiert';


export interface ExternGeimpftJaxTS { 
    externGeimpft?: boolean;
    letzteImpfungDateUnknown?: boolean;
    letzteImpfungDate?: Date;
    impfstoff?: ImpfstoffJaxTS;
    anzahlImpfungen?: number;
    genesen?: boolean;
    positivGetestetDatum?: Date;
    grundimmunisiert?: boolean;
    kontrolliert?: boolean;
    missingForGrundimmunisiertBeforeDecision?: MissingForGrundimmunisiertTS;
    trotzdemVollstaendigGrundimmunisieren?: boolean;
    missingForGrundimmunisiertAfterDecision?: MissingForGrundimmunisiertTS;
    schnellschema: boolean;
}

