/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum FachRolleTS {
    APPLIKATIONS_SUPPORT = 'APPLIKATIONS_SUPPORT',
    FACHVERANTWORTUNG_BAB = 'FACHVERANTWORTUNG_BAB',
    FACHVERANTWORTUNG_BAB_DELEGIERT = 'FACHVERANTWORTUNG_BAB_DELEGIERT',
    ORGANISATIONSVERANTWORTUNG = 'ORGANISATIONSVERANTWORTUNG',
    FACHSUPERVISION = 'FACHSUPERVISION',
    NACHDOKUMENTATION = 'NACHDOKUMENTATION',
    MEDIZINISCHE_NACHDOKUMENTATION = 'MEDIZINISCHE_NACHDOKUMENTATION',
    ORGANISATIONSSUPERVISION = 'ORGANISATIONSSUPERVISION',
    FACHPERSONAL = 'FACHPERSONAL',
    PERSONAL = 'PERSONAL',
    PERSONAL_TELEFON = 'PERSONAL_TELEFON'
}

