/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfdossiereintragJaxTS } from './impfdossiereintrag-jax';
import { ImpfschutzJaxTS } from './impfschutz-jax';
import { ErkrankungJaxTS } from './erkrankung-jax';


export interface ImpfdossierJaxTS { 
    impfdossiereintraege?: Array<ImpfdossiereintragJaxTS>;
    erkrankungen?: Array<ErkrankungJaxTS>;
    impfschutzJax?: ImpfschutzJaxTS;
}

