/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfstoffJaxTS } from './impfstoff-jax';
import { ImpffolgeTS } from './impffolge';


export interface ImpfungJaxTS { 
    impffolge: ImpffolgeTS;
    timestampImpfung: Date;
    ortDerImpfung: string;
    impfstoff: ImpfstoffJaxTS;
    bemerkung?: string;
    impfungNr: number;
    grundimmunisierung: boolean;
    schwanger?: boolean;
    durchfuehrendePerson: string;
    schnellschemaGesetztFuerImpfung: boolean;
}

