/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfdossierStatusTS } from './impfdossier-status';
import { ImpfungJaxTS } from './impfung-jax';
import { ImpfterminJaxTS } from './impftermin-jax';
import { KrankheitJaxTS } from './krankheit-jax';


export interface ImpfdossierSummaryJaxTS { 
    krankheit: KrankheitJaxTS;
    registrierungsnummer: string;
    status: ImpfdossierStatusTS;
    letzteImpfung?: ImpfungJaxTS;
    nextTermin?: ImpfterminJaxTS;
    nichtVerwalteterOdiSelected: boolean;
    externGeimpftConfirmationNeeded: boolean;
    leistungerbringerAgbConfirmationNeeded: boolean;
    freigabeNaechsteImpfung?: Date;
}

