/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateTimeRangeJaxTS } from './date-time-range-jax';
import { ImpfzentrumTagesReportDetailEntryImpfstoffJaxTS } from './impfzentrum-tages-report-detail-entry-impfstoff-jax';


export interface ImpfzentrumTagesReportDetailEntryJaxTS { 
    slotId?: string;
    zeitfenster?: DateTimeRangeJaxTS;
    totalGeplanteImpfungen1?: number;
    totalGeplanteImpfungen2?: number;
    totalGeplanteImpfungenN?: number;
    geplanteImpfungen1UnbekannterImpfstoff?: number;
    geplanteImpfungen2UnbekannterImpfstoff?: number;
    geplanteImpfungenNUnbekannterImpfstoff?: number;
    hasAusstehendeImpfungen?: boolean;
    planungPerImpfstoff?: Set<ImpfzentrumTagesReportDetailEntryImpfstoffJaxTS>;
}

