/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfstofftypTS } from './impfstofftyp';
import { ImpfempfehlungChGrundimmunisierungJaxTS } from './impfempfehlung-ch-grundimmunisierung-jax';
import { ZulassungsStatusTS } from './zulassungs-status';
import { KrankheitJaxTS } from './krankheit-jax';


export interface ImpfstoffJaxTS { 
    id: string;
    name: string;
    displayName?: string;
    hersteller: string;
    code: string;
    covidCertProdCode: string;
    hexFarbe?: string;
    anzahlDosenBenoetigt: number;
    zulassungsStatus: ZulassungsStatusTS;
    informationsLink?: string;
    impfstofftyp: ImpfstofftypTS;
    zulassungsStatusBooster: ZulassungsStatusTS;
    wHoch2Code?: string;
    impfempfehlungen: Array<ImpfempfehlungChGrundimmunisierungJaxTS>;
    eingestellt: boolean;
    krankheiten: Array<KrankheitJaxTS>;
}

