/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfslotDisplayJaxTS } from './impfslot-display-jax';


export interface ImpfslotDisplayDayJaxTS { 
    day: Date;
    dayDisplay?: string;
    /**
     * Liste aller Impfslots des Tages
     */
    readonly krankheitImpfslotDisplayJaxMap?: { [key: string]: Array<ImpfslotDisplayJaxTS>; };
}

