/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImpfzentrumDayStatJaxTS { 
    datum?: Date;
    numberTermin1?: number;
    numberTermin2?: number;
    numberTerminN?: number;
    kapazitaetTermin1?: number;
    kapazitaetTermin2?: number;
    kapazitaetTerminN?: number;
    numberImpfung1?: number;
    numberImpfung2?: number;
    numberImpfungN?: number;
}

