/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImpfslotValidationJaxTS { 
    /**
     * Tag der ersten Impfung als String
     */
    datum1Display: string;
    date1: Date;
    /**
     * Tag der zweiten Impfung als String
     */
    datum2Display: string;
    date2: Date;
    /**
     * Tageskapazitaet der ersten Impfung
     */
    kap1: number;
    /**
     * Tageskapazitaet der zweiten Impfung
     */
    kap2: number;
}

