/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KrankheitIdentifierTS } from './krankheit-identifier';
import { KantonaleBerechtigungTS } from './kantonale-berechtigung';
import { VerarbreichungsartTS } from './verarbreichungsart';


export interface KrankheitSettingsJaxTS { 
    identifier: KrankheitIdentifierTS;
    supportsZertifikat: boolean;
    supportsExternesZertifikat: boolean;
    supportsZweiteImpfungVerzichten: boolean;
    supportsDossierFileUpload: boolean;
    supportsTerminbuchung: boolean;
    supportsImpffolgenEinsUndZwei: boolean;
    supportsMobileImpfteams: boolean;
    supportsContactTracing: boolean;
    warnMinAge?: number;
    supportsErkrankungen: boolean;
    supportsCallcenter: boolean;
    supportsTerminbuchungBeiNichtAufgefuehrtemOdi: boolean;
    supportedVerabreichungsarten: Array<VerarbreichungsartTS>;
    kantonaleBerechtigung: KantonaleBerechtigungTS;
    hasAtleastOneImpfungViewableByKanton: boolean;
    supportsFreigabeSMS: boolean;
    wellEnabled: boolean;
}

