/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrtDerImpfungDisplayNameJaxTS { 
    version?: number;
    timestampErstellt?: Date;
    timestampMutiert?: Date;
    userErstellt?: string;
    userMutiert?: string;
    id?: string;
    name?: string;
    terminverwaltung?: boolean;
    mobilerOrtDerImpfung?: boolean;
    booster?: boolean;
    deaktiviert?: boolean;
    oeffentlich?: boolean;
    glnNummer?: string;
}

