/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum RegistrierungsEingangTS {
    CALLCENTER_REGISTRATION = 'CALLCENTER_REGISTRATION',
    MASSENUPLOAD = 'MASSENUPLOAD',
    ONLINE_REGISTRATION = 'ONLINE_REGISTRATION',
    ORT_DER_IMPFUNG = 'ORT_DER_IMPFUNG'
}

