ALTER TABLE OrtDerImpfung ADD COLUMN IF NOT EXISTS lat DOUBLE NULL;
ALTER TABLE OrtDerImpfung ADD COLUMN IF NOT EXISTS lng DOUBLE NULL;

ALTER TABLE OrtDerImpfung_AUD ADD COLUMN IF NOT EXISTS lat DOUBLE NULL;
ALTER TABLE OrtDerImpfung_AUD ADD COLUMN IF NOT EXISTS lng DOUBLE NULL;

