ALTER TABLE Benutzer ADD COLUMN  IF NOT EXISTS lastUsedSessionId VARCHAR(255) NULL;
ALTER TABLE Benutzer ADD COLUMN  IF NOT EXISTS lastSeenIp VARCHAR(255) NULL;
ALTER TABLE Benutzer ADD COLUMN  IF NOT EXISTS timestampLastSessionId  DATETIME(6) NULL;

ALTER TABLE Benutzer_AUD ADD COLUMN  IF NOT EXISTS lastUsedSessionId VARCHAR(255) NULL;
ALTER TABLE Benutzer_AUD ADD COLUMN  IF NOT EXISTS lastSeenIp VARCHAR(255) NULL;
ALTER TABLE Benutzer_AUD ADD COLUMN  IF NOT EXISTS timestampLastSessionId  DATETIME(6) NULL;
