DROP INDEX IF EXISTS FK_MassenimportRegistrierung_massenimport ON MassenimportRegistrierung;
DROP INDEX IF EXISTS FK_MassenimportRegistrierung_registrierung ON MassenimportRegistrierung;
DROP TABLE MassenimportRegistrierung;
DROP TABLE Massenimport;
