ALTER TABLE Impfung ADD COLUMN timestampVMDL DATETIME(6) NULL;
ALTER TABLE Impfung_AUD ADD COLUMN timestampVMDL DATETIME(6) NULL;

ALTER TABLE Impfung MODIFY lot VARCHAR(32) NOT NULL;
ALTER TABLE Impfstoff MODIFY code VARCHAR(32) NOT NULL;

ALTER TABLE Impfung_AUD MODIFY lot VARCHAR(32);
ALTER TABLE Impfstoff_AUD MODIFY code VARCHAR(32);