ALTER TABLE Impfung ADD COLUMN myCOVIDvacDocId VARCHAR(36) NULL;
ALTER TABLE Impfung ADD COLUMN timestampMyCOVIDvac DATETIME(6) NULL;

ALTER TABLE Impfung_AUD ADD COLUMN myCOVIDvacDocId VARCHAR(36) NULL;
ALTER TABLE Impfung_AUD ADD COLUMN timestampMyCOVIDvac DATETIME(6) NULL;
