export * from './applicationhealth.service';
import { ApplicationhealthService } from './applicationhealth.service';
export * from './benutzer.service';
import { BenutzerService } from './benutzer.service';
export * from './develop.service';
import { DevelopService } from './develop.service';
export * from './dossier.service';
import { DossierService } from './dossier.service';
export * from './download.service';
import { DownloadService } from './download.service';
export * from './geimpft.service';
import { GeimpftService } from './geimpft.service';
export * from './impfdokumentation.service';
import { ImpfdokumentationService } from './impfdokumentation.service';
export * from './impfslot.service';
import { ImpfslotService } from './impfslot.service';
export * from './impfstoff.service';
import { ImpfstoffService } from './impfstoff.service';
export * from './kontrolle.service';
import { KontrolleService } from './kontrolle.service';
export * from './korrektur.service';
import { KorrekturService } from './korrektur.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './odibenutzer.service';
import { OdibenutzerService } from './odibenutzer.service';
export * from './onboarding.service';
import { OnboardingService } from './onboarding.service';
export * from './ortderimpfung.service';
import { OrtderimpfungService } from './ortderimpfung.service';
export * from './personalien-suche.service';
import { PersonalienSucheService } from './personalien-suche.service';
export * from './properties.service';
import { PropertiesService } from './properties.service';
export * from './public.service';
import { PublicService } from './public.service';
export * from './registrierung.service';
import { RegistrierungService } from './registrierung.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './reports-sync.service';
import { ReportsSyncService } from './reports-sync.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './stammdaten.service';
import { StammdatenService } from './stammdaten.service';
export * from './stat.service';
import { StatService } from './stat.service';
export * from './systemadministration.service';
import { SystemadministrationService } from './systemadministration.service';
export * from './terminbuchung.service';
import { TerminbuchungService } from './terminbuchung.service';
export * from './zertifikat.service';
import { ZertifikatService } from './zertifikat.service';
export const APIS = [ApplicationhealthService, BenutzerService, DevelopService, DossierService, DownloadService, GeimpftService, ImpfdokumentationService, ImpfslotService, ImpfstoffService, KontrolleService, KorrekturService, MessagesService, OdibenutzerService, OnboardingService, OrtderimpfungService, PersonalienSucheService, PropertiesService, PublicService, RegistrierungService, ReportsService, ReportsSyncService, SettingsService, StammdatenService, StatService, SystemadministrationService, TerminbuchungService, ZertifikatService];
