/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { PersonalienJaxTS } from '../model/personalien-jax';
// @ts-ignore
import { RegistrierungSearchResponseWithRegnummerJaxTS } from '../model/registrierung-search-response-with-regnummer-jax';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class PersonalienSucheService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param geburtsdatum 
     * @param name 
     * @param vorname 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public personalienSucheRegResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<PersonalienJaxTS>>;
    public personalienSucheRegResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<PersonalienJaxTS>>>;
    public personalienSucheRegResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<PersonalienJaxTS>>>;
    public personalienSucheRegResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (geburtsdatum === null || geburtsdatum === undefined) {
            throw new Error('Required parameter geburtsdatum was null or undefined when calling personalienSucheRegResourceSuchen.');
        }
        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling personalienSucheRegResourceSuchen.');
        }
        if (vorname === null || vorname === undefined) {
            throw new Error('Required parameter vorname was null or undefined when calling personalienSucheRegResourceSuchen.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.get<Array<PersonalienJaxTS>>(`${this.configuration.basePath}/api/v1/reg/personalien-suche/suchen/${encodeURIComponent(String(vorname))}/${encodeURIComponent(String(name))}/${encodeURIComponent(String(geburtsdatum))}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param geburtsdatum 
     * @param name 
     * @param uvci 
     * @param vorname 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public personalienSucheRegResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>;
    public personalienSucheRegResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>>;
    public personalienSucheRegResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>>;
    public personalienSucheRegResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (geburtsdatum === null || geburtsdatum === undefined) {
            throw new Error('Required parameter geburtsdatum was null or undefined when calling personalienSucheRegResourceSuchenUvci.');
        }
        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling personalienSucheRegResourceSuchenUvci.');
        }
        if (uvci === null || uvci === undefined) {
            throw new Error('Required parameter uvci was null or undefined when calling personalienSucheRegResourceSuchenUvci.');
        }
        if (vorname === null || vorname === undefined) {
            throw new Error('Required parameter vorname was null or undefined when calling personalienSucheRegResourceSuchenUvci.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.get<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>(`${this.configuration.basePath}/api/v1/reg/personalien-suche/suchen/${encodeURIComponent(String(vorname))}/${encodeURIComponent(String(name))}/${encodeURIComponent(String(geburtsdatum))}/${encodeURIComponent(String(uvci))}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param geburtsdatum 
     * @param name 
     * @param vorname 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public personalienSucheResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>;
    public personalienSucheResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>>;
    public personalienSucheResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>>;
    public personalienSucheResourceSuchen(geburtsdatum: Date, name: string, vorname: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (geburtsdatum === null || geburtsdatum === undefined) {
            throw new Error('Required parameter geburtsdatum was null or undefined when calling personalienSucheResourceSuchen.');
        }
        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling personalienSucheResourceSuchen.');
        }
        if (vorname === null || vorname === undefined) {
            throw new Error('Required parameter vorname was null or undefined when calling personalienSucheResourceSuchen.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.get<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>(`${this.configuration.basePath}/api/v1/web/personalien-suche/suchen/${encodeURIComponent(String(vorname))}/${encodeURIComponent(String(name))}/${encodeURIComponent(String(geburtsdatum))}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param geburtsdatum 
     * @param name 
     * @param uvci 
     * @param vorname 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public personalienSucheResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>;
    public personalienSucheResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>>;
    public personalienSucheResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>>;
    public personalienSucheResourceSuchenUvci(geburtsdatum: Date, name: string, uvci: string, vorname: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (geburtsdatum === null || geburtsdatum === undefined) {
            throw new Error('Required parameter geburtsdatum was null or undefined when calling personalienSucheResourceSuchenUvci.');
        }
        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling personalienSucheResourceSuchenUvci.');
        }
        if (uvci === null || uvci === undefined) {
            throw new Error('Required parameter uvci was null or undefined when calling personalienSucheResourceSuchenUvci.');
        }
        if (vorname === null || vorname === undefined) {
            throw new Error('Required parameter vorname was null or undefined when calling personalienSucheResourceSuchenUvci.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.get<Array<RegistrierungSearchResponseWithRegnummerJaxTS>>(`${this.configuration.basePath}/api/v1/web/personalien-suche/suchen/${encodeURIComponent(String(vorname))}/${encodeURIComponent(String(name))}/${encodeURIComponent(String(geburtsdatum))}/${encodeURIComponent(String(uvci))}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
