/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { DashboardJaxTS } from '../model/dashboard-jax';
// @ts-ignore
import { ImpffolgeTS } from '../model/impffolge';
// @ts-ignore
import { ImpfslotJaxTS } from '../model/impfslot-jax';
// @ts-ignore
import { KrankheitIdentifierTS } from '../model/krankheit-identifier';
// @ts-ignore
import { NextFreierTerminJaxTS } from '../model/next-freier-termin-jax';
// @ts-ignore
import { TermineAbsagenJaxTS } from '../model/termine-absagen-jax';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class TerminbuchungService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param impfslot2Id 
     * @param krankheit 
     * @param odiId 
     * @param registrierungsnummer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceCreateAdHocTermin1AndBucheTermin2(impfslot2Id: string, krankheit: KrankheitIdentifierTS, odiId: string, registrierungsnummer: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<DashboardJaxTS>;
    public terminbuchungResourceCreateAdHocTermin1AndBucheTermin2(impfslot2Id: string, krankheit: KrankheitIdentifierTS, odiId: string, registrierungsnummer: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<DashboardJaxTS>>;
    public terminbuchungResourceCreateAdHocTermin1AndBucheTermin2(impfslot2Id: string, krankheit: KrankheitIdentifierTS, odiId: string, registrierungsnummer: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<DashboardJaxTS>>;
    public terminbuchungResourceCreateAdHocTermin1AndBucheTermin2(impfslot2Id: string, krankheit: KrankheitIdentifierTS, odiId: string, registrierungsnummer: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (impfslot2Id === null || impfslot2Id === undefined) {
            throw new Error('Required parameter impfslot2Id was null or undefined when calling terminbuchungResourceCreateAdHocTermin1AndBucheTermin2.');
        }
        if (krankheit === null || krankheit === undefined) {
            throw new Error('Required parameter krankheit was null or undefined when calling terminbuchungResourceCreateAdHocTermin1AndBucheTermin2.');
        }
        if (odiId === null || odiId === undefined) {
            throw new Error('Required parameter odiId was null or undefined when calling terminbuchungResourceCreateAdHocTermin1AndBucheTermin2.');
        }
        if (registrierungsnummer === null || registrierungsnummer === undefined) {
            throw new Error('Required parameter registrierungsnummer was null or undefined when calling terminbuchungResourceCreateAdHocTermin1AndBucheTermin2.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.put<DashboardJaxTS>(`${this.configuration.basePath}/api/v1/web/terminbuchung/createAdHocTermin1AndBucheTermin2/krankheit/${encodeURIComponent(String(krankheit))}/${encodeURIComponent(String(registrierungsnummer))}/${encodeURIComponent(String(odiId))}/${encodeURIComponent(String(impfslot2Id))}`,
        null,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param impffolge 
     * @param krankheit 
     * @param ortDerImpfungId 
     * @param nextFreierTerminJaxTS 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceGetFreieImpftermine(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<ImpfslotJaxTS>>;
    public terminbuchungResourceGetFreieImpftermine(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<ImpfslotJaxTS>>>;
    public terminbuchungResourceGetFreieImpftermine(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<ImpfslotJaxTS>>>;
    public terminbuchungResourceGetFreieImpftermine(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (impffolge === null || impffolge === undefined) {
            throw new Error('Required parameter impffolge was null or undefined when calling terminbuchungResourceGetFreieImpftermine.');
        }
        if (krankheit === null || krankheit === undefined) {
            throw new Error('Required parameter krankheit was null or undefined when calling terminbuchungResourceGetFreieImpftermine.');
        }
        if (ortDerImpfungId === null || ortDerImpfungId === undefined) {
            throw new Error('Required parameter ortDerImpfungId was null or undefined when calling terminbuchungResourceGetFreieImpftermine.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.post<Array<ImpfslotJaxTS>>(`${this.configuration.basePath}/api/v1/web/terminbuchung/termine/frei/krankheit/${encodeURIComponent(String(krankheit))}/${encodeURIComponent(String(ortDerImpfungId))}/${encodeURIComponent(String(impffolge))}`,
        nextFreierTerminJaxTS,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param impffolge 
     * @param krankheit 
     * @param ortDerImpfungId 
     * @param nextFreierTerminJaxTS 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceGetNextFreierImpftermin(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<NextFreierTerminJaxTS>;
    public terminbuchungResourceGetNextFreierImpftermin(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<NextFreierTerminJaxTS>>;
    public terminbuchungResourceGetNextFreierImpftermin(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<NextFreierTerminJaxTS>>;
    public terminbuchungResourceGetNextFreierImpftermin(impffolge: ImpffolgeTS, krankheit: KrankheitIdentifierTS, ortDerImpfungId: string, nextFreierTerminJaxTS?: NextFreierTerminJaxTS, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (impffolge === null || impffolge === undefined) {
            throw new Error('Required parameter impffolge was null or undefined when calling terminbuchungResourceGetNextFreierImpftermin.');
        }
        if (krankheit === null || krankheit === undefined) {
            throw new Error('Required parameter krankheit was null or undefined when calling terminbuchungResourceGetNextFreierImpftermin.');
        }
        if (ortDerImpfungId === null || ortDerImpfungId === undefined) {
            throw new Error('Required parameter ortDerImpfungId was null or undefined when calling terminbuchungResourceGetNextFreierImpftermin.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.post<NextFreierTerminJaxTS>(`${this.configuration.basePath}/api/v1/web/terminbuchung/termine/nextfrei/krankheit/${encodeURIComponent(String(krankheit))}/${encodeURIComponent(String(ortDerImpfungId))}/${encodeURIComponent(String(impffolge))}`,
        nextFreierTerminJaxTS,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param impffolge 
     * @param impfslotId 
     * @param registrierungsnummer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceReservieren(impffolge: ImpffolgeTS, impfslotId: string, registrierungsnummer: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any>;
    public terminbuchungResourceReservieren(impffolge: ImpffolgeTS, impfslotId: string, registrierungsnummer: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpResponse<any>>;
    public terminbuchungResourceReservieren(impffolge: ImpffolgeTS, impfslotId: string, registrierungsnummer: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpEvent<any>>;
    public terminbuchungResourceReservieren(impffolge: ImpffolgeTS, impfslotId: string, registrierungsnummer: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any> {
        if (impffolge === null || impffolge === undefined) {
            throw new Error('Required parameter impffolge was null or undefined when calling terminbuchungResourceReservieren.');
        }
        if (impfslotId === null || impfslotId === undefined) {
            throw new Error('Required parameter impfslotId was null or undefined when calling terminbuchungResourceReservieren.');
        }
        if (registrierungsnummer === null || registrierungsnummer === undefined) {
            throw new Error('Required parameter registrierungsnummer was null or undefined when calling terminbuchungResourceReservieren.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.put<any>(`${this.configuration.basePath}/api/v1/web/terminbuchung/reservieren/${encodeURIComponent(String(registrierungsnummer))}/${encodeURIComponent(String(impfslotId))}/${encodeURIComponent(String(impffolge))}`,
        null,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param krankheit 
     * @param registrierungsnummer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceTerminAbsagen(krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<DashboardJaxTS>;
    public terminbuchungResourceTerminAbsagen(krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<DashboardJaxTS>>;
    public terminbuchungResourceTerminAbsagen(krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<DashboardJaxTS>>;
    public terminbuchungResourceTerminAbsagen(krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (krankheit === null || krankheit === undefined) {
            throw new Error('Required parameter krankheit was null or undefined when calling terminbuchungResourceTerminAbsagen.');
        }
        if (registrierungsnummer === null || registrierungsnummer === undefined) {
            throw new Error('Required parameter registrierungsnummer was null or undefined when calling terminbuchungResourceTerminAbsagen.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.delete<DashboardJaxTS>(`${this.configuration.basePath}/api/v1/web/terminbuchung/cancel/krankheit/${encodeURIComponent(String(krankheit))}/${encodeURIComponent(String(registrierungsnummer))}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Absagen aller Termine eines bestimmten Datums und Impffolge eines OdI falls zB. aus logistischen Gruenden an einem Tag nicht geimpft werden kann
     * @param termineAbsagenJaxTS 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceTermineAbsagenForOdiAndDatum(termineAbsagenJaxTS?: TermineAbsagenJaxTS, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any>;
    public terminbuchungResourceTermineAbsagenForOdiAndDatum(termineAbsagenJaxTS?: TermineAbsagenJaxTS, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpResponse<any>>;
    public terminbuchungResourceTermineAbsagenForOdiAndDatum(termineAbsagenJaxTS?: TermineAbsagenJaxTS, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<HttpEvent<any>>;
    public terminbuchungResourceTermineAbsagenForOdiAndDatum(termineAbsagenJaxTS?: TermineAbsagenJaxTS, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.post<any>(`${this.configuration.basePath}/api/v1/web/terminbuchung/absagen`,
        termineAbsagenJaxTS,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param impfslotNId 
     * @param krankheit 
     * @param registrierungsnummer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceUmbuchenBooster(impfslotNId: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<DashboardJaxTS>;
    public terminbuchungResourceUmbuchenBooster(impfslotNId: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<DashboardJaxTS>>;
    public terminbuchungResourceUmbuchenBooster(impfslotNId: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<DashboardJaxTS>>;
    public terminbuchungResourceUmbuchenBooster(impfslotNId: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (impfslotNId === null || impfslotNId === undefined) {
            throw new Error('Required parameter impfslotNId was null or undefined when calling terminbuchungResourceUmbuchenBooster.');
        }
        if (krankheit === null || krankheit === undefined) {
            throw new Error('Required parameter krankheit was null or undefined when calling terminbuchungResourceUmbuchenBooster.');
        }
        if (registrierungsnummer === null || registrierungsnummer === undefined) {
            throw new Error('Required parameter registrierungsnummer was null or undefined when calling terminbuchungResourceUmbuchenBooster.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.put<DashboardJaxTS>(`${this.configuration.basePath}/api/v1/web/terminbuchung/umbuchenBooster/krankheit/${encodeURIComponent(String(krankheit))}/${encodeURIComponent(String(registrierungsnummer))}/${encodeURIComponent(String(impfslotNId))}`,
        null,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param impfslot1Id 
     * @param impfslot2Id 
     * @param krankheit 
     * @param registrierungsnummer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public terminbuchungResourceUmbuchenGrundimmunisierung(impfslot1Id: string, impfslot2Id: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<DashboardJaxTS>;
    public terminbuchungResourceUmbuchenGrundimmunisierung(impfslot1Id: string, impfslot2Id: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<DashboardJaxTS>>;
    public terminbuchungResourceUmbuchenGrundimmunisierung(impfslot1Id: string, impfslot2Id: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<DashboardJaxTS>>;
    public terminbuchungResourceUmbuchenGrundimmunisierung(impfslot1Id: string, impfslot2Id: string, krankheit: KrankheitIdentifierTS, registrierungsnummer: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (impfslot1Id === null || impfslot1Id === undefined) {
            throw new Error('Required parameter impfslot1Id was null or undefined when calling terminbuchungResourceUmbuchenGrundimmunisierung.');
        }
        if (impfslot2Id === null || impfslot2Id === undefined) {
            throw new Error('Required parameter impfslot2Id was null or undefined when calling terminbuchungResourceUmbuchenGrundimmunisierung.');
        }
        if (krankheit === null || krankheit === undefined) {
            throw new Error('Required parameter krankheit was null or undefined when calling terminbuchungResourceUmbuchenGrundimmunisierung.');
        }
        if (registrierungsnummer === null || registrierungsnummer === undefined) {
            throw new Error('Required parameter registrierungsnummer was null or undefined when calling terminbuchungResourceUmbuchenGrundimmunisierung.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }


    return this.httpClient.put<DashboardJaxTS>(`${this.configuration.basePath}/api/v1/web/terminbuchung/umbuchenGrundimmunisierung/krankheit/${encodeURIComponent(String(krankheit))}/${encodeURIComponent(String(registrierungsnummer))}/${encodeURIComponent(String(impfslot1Id))}/${encodeURIComponent(String(impfslot2Id))}`,
        null,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
