### Hello-Resteasy
GET http://localhost:8080/api/v1/hello-resteasy

### Step 1: Registrierung mit Username hansli schreiben
POST http://localhost:8080/api/v1/reg/registration/registrieren
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
	"ampel": "GREEN",
	"risikogruppe": true,
	"beruflicheTaetigkeit": "ANDERE",
	"lebensumstaende": "ANDERE",
	"adresse": {
		"adresse1": "string",
		"adresse2": "string",
		"ort": "string",
		"plz": "string"
	},
	"bemerkung": "string",
	"geburtsdatum": "1930-12-11",
	"geschlecht": "MAENNLICH",
	"mail": "hansli@mailbucket.dvbern.ch",
	"name": "string",
	"telefon": "string",
	"vorname": "string",
	"krankenkasse": "KPT",
	"krankenkasseKartenNr": "12345678"
}

### Step 2: Registrierung mit Registrierungsnummer 12345 lesen
GET http://localhost:8080/api/v1/reg/dossier/dashboard/N8XV4

### Step 3: Liste der vorhandenen Orte der Impfung anzeigen (nur Displayname)
GET http://localhost:8080/api/v1/reg/dossier/odi/all

### Step 4: Freie Termine fuer meinen OrtDerImpfung anzeigen
GET http://localhost:8080/api/v1/ortderimpfung/termine/frei/1f3821fd-22db-47c6-a341-2c7d1a7ac5ee

### Step 5: Termine buchen
PUT http://localhost:8080/api/v1/reg/dossier/buchen
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
	"registrierungsnummer": "G8GZ4",
	"termin1Id": "61ccbc4b-734c-4ce0-b4c8-60f3269f99a0",
	"termin2Id": "ce4626fc-bf06-4571-ba77-3d17fe9e11ee"
}

### Registrierungsbestaetigung herunterladen
POST http://localhost:8080/api/v1/reg/dossier/download/registrierungsbestaetigung/Y5BA4D
Accept: */*
Cache-Control: no-cache
Content-Type: application/pdf

{}

### Terminbestaetigung herunterladen
POST http://localhost:8080/api/v1/reg/dossier/download/terminbestaetigung/Y5BA4D
Accept: */*
Cache-Control: no-cache
Content-Type: application/pdf

{}