/*
 * Copyright (C) 2022 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum BeruflicheTaetigkeitZH {
    GESPERSONALMITPATKONTAKTINTENSIV = 'GES_PERSONAL_MIT_PAT_KONTAKT_INTENSIV',
    GESPERSONALMITPATKONTAKT = 'GES_PERSONAL_MIT_PAT_KONTAKT',
    GESPERSONALOHNEPATKONTAKT = 'GES_PERSONAL_OHNE_PAT_KONTAKT',
    BERUFMITKUNDENKONTAKT = 'BERUF_MIT_KUNDENKONTAKT',
    BERUFMITAKTINGROARBGRUP = 'BERUF_MIT_AKT_IN_GRO_ARB_GRUP',
    BERUFMITHOMEOFFICEMOEGLICH = 'BERUF_MIT_HOMEOFFICE_MOEGLICH',
    BETREUUNGVONGEFAERDPERSON = 'BETREUUNG_VON_GEFAERD_PERSON',
    PERSONALINGEMEINSCHAFTSEIN = 'PERSONAL_IN_GEMEINSCHAFTSEIN',
    NICHTERWERBSTAETIG = 'NICHT_ERWERBSTAETIG',
    ANDERE = 'ANDERE',
}
