/*
 * Copyright (C) 2022 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * Covid Certificate API Gateway Service
 * Rest API for Covid Certificate API Gateway Service.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.dvbern.oss.vacme.entities.covidcertificate;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * CovidCertificateCreateResponseDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-05-25T17"
	+ ":13:54.751Z[GMT]")
public class CovidCertificateCreateResponseDto {
	@JsonProperty("pdf")
	private byte[] pdf = null;

	@JsonProperty("qrCode")
	private byte[] qrCode = null;

	@JsonProperty("uvci")
	private String uvci = null;

	public CovidCertificateCreateResponseDto pdf(byte[] pdf) {
		this.pdf = pdf;
		return this;
	}

	/**
	 * Get pdf
	 *
	 * @return pdf
	 **/
	@Schema(description = "")
	public byte[] getPdf() {
		return pdf;
	}

	public void setPdf(byte[] pdf) {
		this.pdf = pdf;
	}

	public CovidCertificateCreateResponseDto qrCode(byte[] qrCode) {
		this.qrCode = qrCode;
		return this;
	}

	/**
	 * Get qrCode
	 *
	 * @return qrCode
	 **/
	@Schema(description = "")
	public byte[] getQrCode() {
		return qrCode;
	}

	public void setQrCode(byte[] qrCode) {
		this.qrCode = qrCode;
	}

	public CovidCertificateCreateResponseDto uvci(String uvci) {
		this.uvci = uvci;
		return this;
	}

	/**
	 * Get uvci
	 *
	 * @return uvci
	 **/
	@Schema(description = "")
	public String getUvci() {
		return uvci;
	}

	public void setUvci(String uvci) {
		this.uvci = uvci;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CovidCertificateCreateResponseDto covidCertificateCreateResponseDto = (CovidCertificateCreateResponseDto) o;
		return Arrays.equals(this.pdf, covidCertificateCreateResponseDto.pdf) &&
			Arrays.equals(this.qrCode, covidCertificateCreateResponseDto.qrCode) &&
			Objects.equals(this.uvci, covidCertificateCreateResponseDto.uvci);
	}

	@Override
	public int hashCode() {
		return Objects.hash(Arrays.hashCode(pdf), Arrays.hashCode(qrCode), uvci);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CovidCertificateCreateResponseDto {\n");

		sb.append("    pdf: ").append(toIndentedString(pdf)).append("\n");
		sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
		sb.append("    uvci: ").append(toIndentedString(uvci)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
