/*
 * Copyright (C) 2022 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * Covid Certificate API Gateway Service
 * Rest API for Covid Certificate API Gateway Service.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.dvbern.oss.vacme.entities.covidcertificate;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RevocationDto
 */

public class RevocationDto {

	@JsonProperty("uvci")
	private String uvci = null;

	@JsonProperty("otp")
	private String otp = null;

	public RevocationDto uvci(String uvci) {
		this.uvci = uvci;
		return this;
	}

	public String getUvci() {
		return uvci;
	}

	public void setUvci(String uvci) {
		this.uvci = uvci;
	}

	public RevocationDto otp(String otp) {
		this.otp = otp;
		return this;
	}

	public String getOtp() {
		return otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RevocationDto dto = (RevocationDto) o;
		return Objects.equals(this.uvci, dto.uvci) &&
			Objects.equals(this.otp, dto.otp);
	}

	@Override
	public int hashCode() {
		return Objects.hash(uvci, otp);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RevocationDto {\n");
		sb.append("    uvci: ").append(toIndentedString(uvci)).append("\n");
		sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
