/*
 * Copyright (C) 2022 DV Bern AG, Switzerland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package ch.dvbern.oss.vacme.entities.base;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(enumeration = {"COVID_ZERTIFIKAT_ENABLED", "PRIO_FREIGEGEBEN_BIS"})
public enum ApplicationPropertyKey {

	PRIO_FREIGEGEBEN_BIS,
	VACME_ASYNC_DOCUMENT_CREATION_DISABLED,
	VACME_BOOSTER_STATUSMOVER_JOB_DISABLED,
	VACME_BOOSTER_RULE_ENGINE_JOB_DISABLED,
	VACME_BOOSTER_RULE_ENGINE_JOB_BATCH_SIZE,
	VACME_BOOSTER_RULE_ENGINE_JOB_PARTITIONS,
	VACME_BOOSTER_STATUSMOVER_JOB_BATCH_SIZE,
	VACME_BOOSTER_FREIGABE_JOB_DISABLED,
	VACME_BOOSTER_FREIGABE_NOTIFICATION_DISABLED,
	VACME_BOOSTER_FREIGABE_NOTIFICATION_TERMIN_N_DISABLED,
	VACME_BOOSTER_FREIGABE_JOB_BATCH_SIZE,
	VACME_BOOSTER_FREIGABE_SMS_SLEEP_TIME_MS,
	VACME_COVID_CERT_BATCHJOB_DISABLED,
	VACME_COVID_CERT_BATCHJOB_POST_DISABLED,
	VACME_COVID_CERT_BATCHJOB_REVOC_ONLINE_DISABLED,
	VACME_COVID_CERT_BATCHJOB_REVOC_POST_DISABLED,
	VACME_REGISTRIERUNG_AUTO_ABSCHLIESSEN_JOB_DISABLED,
	VACME_DEACTIVATE_UNUSED_USERACCOUNTS_JOB_DISABLED,
	VACME_DEACTIVATE_UNUSED_USERACCOUNTS_AFTER_MINUTES,
	VACME_MASSENVERARBEITUNGQUEUE_PROCESSING_JOB_DISABLED,
	VACME_MASSENVERARBEITUNGQUEUE_PROCESSING_JOB_BATCH_SIZE,
	VACME_MASSENVERARBEITUNGQUEUE_PROCESSING_JOB_PARTITIONS,
	COVID_ZERTIFIKAT_ENABLED,
	VACME_COVIDAPI_PS_BATCHSIZE,
	VACME_COVIDAPI_ONLINE_PS_BATCHJOB_LOCK,
	VACME_COVIDAPI_POST_PS_BATCHJOB_LOCK,
	VACME_MIGRATION_ZERTIFIKAT_REGEX, // Regex, der die ExternalId entsprechen muss, damit die Migrierten Regs verarbeitet werden
	VACME_COVIDAPI_REVOCATION_ONLINE_PS_BATCHJOB_LOCK,
	VACME_COVIDAPI_REVOCATION_POST_PS_BATCHJOB_LOCK,
	VACME_ONBOARDING_BRIEF_DISABLED,
	VACME_ONBOARDING_BRIEF_BATCHJOB_LOCK,
	VACME_ONBOARDING_BRIEF_BATCHSIZE,
	VACME_GEOCODING_ENABLED,
	VMDL_CRON_DISABLED,
	VMDL_CRON_MANUAL_TRIGGER_MULTIPLICATOR,
	VMDL_CRON_3QUERIES,
	DISTANCE_BETWEEN_IMPFUNGEN_DISIRED,
	DISTANCE_BETWEEN_IMPFUNGEN_TOLERANCE_BEFORE,
	DISTANCE_BETWEEN_IMPFUNGEN_TOLERANCE_AFTER,
	MINUTES_BETWEEN_INFO_UPDATES,
	SHOW_ONBOARDING_WELCOME_TEXT,
	MINUTES_BETWEEN_PHONENUMBER_UPDATE,
	KORREKTUR_EMAIL_TELEPHONE,
	SELBSTZAHLER_FACHAPPLIKATION_ENABLED,
	SELBSTZAHLER_PORTAL_ENABLED,
	VACME_CRON_ODI_TERMINE_FREI_DISABLED,
	VACME_CRON_GLOBAL_FREI_TERMINE_DISABLED,
	VACME_CRON_HAS_IMPFUNG_FOR_KANTON_DISABLED,
	ODI_FILTER_WELL_FOR_GALENICA_ENABLED,
	ARCHIVIERUNG_JOB_BATCH_SIZE

}
